name: send files to search

on:
    push:
        paths:
            - "**.md"
            - "!node_modules/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - id: file_changes
              uses: trilom/file-changes-action@v1
              with:
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
            - name: do file stuff
              uses: ./ # Uses an action in the root directory
              with:
                  algoliaAdminKey: ${{ secrets.ALGOLIA_ADMIN_KEY }}
                  new-files: ${{ steps.file_changes.outputs.files_added }}
                  updated-files: ${{ steps.file_changes.outputs.files_modified }}
                  deleted-files: ${{ steps.file_changes.outputs.files_deleted }}
